### ISSUE TITLE
Cannot use the letters 'as' in itemsPerPage expression, causes error.

### ISSUE THREAD

**Issue by MrHus** [michaelbromley/angularUtils-pagination#10]
I have a controller called the "DeceasedController" which I use with controller as in the following manner: "DeceasedController as deceasedController". 

I get an error when I use:

```
itemsPerPage: deceasedController.size
```

The error is:

```
[$parse:syntax] Syntax Error: Token 'asedController.pageSize' is an unexpected token at column 37 of the expression [deceasedController.meals | filter:q asedController.pageSize] starting at [asedController.pageSize].
```

You can see it on this plunker here (modified from the demo):
http://plnkr.co/edit/pgG4FwaOnvdkoZbYZ3BA?p=preview

The reason for this is that the regex in dirPagination.js in the dirPaginationCompileFn
function treats the string 'as' in a special way.

Somehow matches 'as' in the wrong way, any expression containing the letters 'as' fails.

So masterController, blasterController etc etc cannot be used.

**Comment by michaelbromley** [comment]
Hi,

This issue was fixed in [release 0.9.1](https://github.com/michaelbromley/angularUtils-pagination/releases). Please update to the latest version and let me know if there is still an issue.
