### ISSUE TITLE
Name of bower package

### ISSUE THREAD

**Issue by Nainterceptor** [michaelbromley/angularUtils-pagination#12]
Hello @michaelbromley,

Your package is registered in bower.io as "angular-utils-pagination", so in the bower.js, I can see "name": "angularUtils-pagination".
Is it normal ? I think this difference may cause problemes with a override in a project.
I've found a workaround for now.

Have a nice day,
Gaël

**Comment by michaelbromley** [comment]
I discovered that bower does not allow camelCased package names, which is why I used the lowercase hyphen-separated version originally. Can you explain how it causes a problem this way?

**Comment by Nainterceptor** [comment]
I use wiredeps to link deps to my project. I use some overrides in my bower project and I can't override your main, I don't know why... I think it's linked to the difference between bower.json name and bower.io name.

I'm not sure about this bug :)
