### ISSUE TITLE
Pagination throw exception when dismissing the $mddialog Angularjs

### ISSUE THREAD

**Issue by hvhoat** [michaelbromley/angularUtils-pagination#13]
Hi everyone,
the pagination works well but when displaying a dialog and dismiss then browser is frozen and show exception

Error in console (debug mode): 
> pagination directive: the itemsPerPage id argument (id: __default) does not match a registered pagination-id.

Please help me for it. Thank you so much.

**Comment by michaelbromley** [comment]
Hi, this repo is just for the package release. Please open an issue in the main repo (https://github.com/michaelbromley/angularUtils/issues) and also please include the relevant code (controller/view) so I can see what is going on.
