### ISSUE TITLE
Bower installation issue

### ISSUE THREAD

**Issue by LeleDev** [michaelbromley/angularUtils-pagination#7]
```bower install angularUtils-pagination``` gives the following error:
``` bower ENOTFOUND     Package angularUtils-pagination not found ```

**Comment by michaelbromley** [comment]
Hi, the command should be `bower install angular-utils-pagination` - not the hyphenation. It is that way due to restrictions on how Bower packages may be named.

**Comment by LeleDev** [comment]
Ok you are right, it is working... the weird thing is that the installed package is named angularUtils-pagination :/

**Comment by michaelbromley** [comment]
Yes, I wanted to call it that since that is the name of the repo. However, registering it with the Bower registry kept failing and I finally found out that it was due to the uppercase U.
